scarc:
  name: 'Oregon State University Libraries and Press. Special Collections and Archives Research Center'
  description: "The Oregon State University Libraries Special Collections and Archives Research Center, located on the 5th floor of The Valley Library, is home to the university’s unique collections of manuscripts, archives, photographs, and books. We collect in five main areas: the History of OSU, the History of Science, Natural Resources, Multiculturalism in Oregon and Hops and Brewing History. We also administer the university's Records Management Program, are home to a robust Oral History Program, and have numerous Rare Books collections."
  contact_html: |
    <div class="al-repository-contact-info"><a href="mailto:scarc@oregonstate.edu">scarc@oregonstate.edu</a></div>
    <div class="al-repository-contact-phone">(541) 737-2075</div>
  location_html: |
    <div class="al-repository-street-address-building">121 Valley Library</div>
    <div class="al-repository-street-address-address1">Oregon State University</div>
    <div class="al-repository-street-address-city_state_zip_country">Corvallis, OR 97331-3411, USA</div>
  thumbnail_url: 'https://scarc.library.oregonstate.edu/images/library-fall.jpg'
  request_types:
    google_form:
      request_url: 'https://docs.google.com/abc123'
      request_mappings: 'collection_name=abc&eadid=123'
